DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PGTABLE1;

CREATE TABLE CUSTOMER
(
   SSN char(10),
   FIRSTNAME varchar(64),
   LASTNAME varchar(64),
   CONSTRAINT CUSTOMER_PK PRIMARY KEY(SSN)
);

CREATE TABLE PGTABLE1
(
   ID SERIAL,
   FIELD1 varchar(64),
   FIELD2 varchar(64),
   CONSTRAINT PGTABLE1_PK PRIMARY KEY(ID)
);

INSERT INTO CUSTOMER (SSN,FIRSTNAME,LASTNAME) VALUES ('123456789','David','Ortiz');
INSERT INTO CUSTOMER (SSN,FIRSTNAME,LASTNAME) VALUES ('987654321','Dustin','Pedrioa');

INSERT INTO PGTABLE1 (FIELD1,FIELD2) VALUES ('Blah11','Blah12');
INSERT INTO PGTABLE1 (FIELD1,FIELD2) VALUES ('Blah21','Blah22');
