DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS MSTABLE1;

CREATE TABLE CUSTOMER
(
   SSN char(10),
   FIRSTNAME varchar(64),
   LASTNAME varchar(64),
   CONSTRAINT CUSTOMER_PK PRIMARY KEY(SSN)
);

CREATE TABLE MSTABLE1
(
   ID char(10),
   FIELD1 varchar(64),
   FIELD2 varchar(64),
   CONSTRAINT PGTABLE1_PK PRIMARY KEY(ID)
);

INSERT INTO CUSTOMER (SSN,FIRSTNAME,LASTNAME) VALUES ('123456789','Jackie','Bradley');
INSERT INTO CUSTOMER (SSN,FIRSTNAME,LASTNAME) VALUES ('987654321','Mookie','Betts');

INSERT INTO MSTABLE1 (ID, FIELD1,FIELD2) VALUES ('1', 'Blah11','Blah12');
INSERT INTO MSTABLE1 (ID, FIELD1,FIELD2) VALUES ('2', 'Blah21','Blah22');
